# Generated by Django 5.2.1 on 2025-05-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='login_user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
