# Generated by Django 5.2.1 on 2025-05-13 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itemform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='itemForm',
            new_name='Item',
        ),
    ]
