# Generated by Django 5.2.1 on 2025-05-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_itemform_item'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'code'), name='unique_item_name_code'),
        ),
    ]
