# Generated by Django 5.2.1 on 2025-05-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_unique_item_name_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
