# Generated by Django 5.2.1 on 2025-05-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_item_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_name_code',
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
