# Generated by Django 5.2.1 on 2025-05-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_item_unique_item_name_code_alter_item_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'code'), name='unique_item_name_code'),
        ),
    ]
